### ISSUE TITLE
table无法使用await dp.create() ?

### ISSUE THREAD

**Issue by gitee1** [hairyf/u-draw#31]
你好，我想使用table模块生成一个餐饮小票，最终生成图片。
我从https://ext.dcloud.net.cn/plugin?id=3237 中下载了示例项目。
demo中的table.vue，我看到使用setTimeout包裹dp.create()方法。
![image](https://user-images.githubusercontent.com/38205338/177296993-b4b79b33-fb9b-4756-b746-758720a1907d.png)

我尝试将setTimeout替换成文档中的await dp.create()，但是这样基本上就无法预览到生成的canvas了。问题如下这个视频展示：

https://user-images.githubusercontent.com/38205338/177296435-be2914ae-74a7-4750-9d50-608ae290e3cc.mp4

目前参考demo的代码，暂时使用了setTimeout方法解决。

**Comment by TuiMao233** [comment]
这个问题目前还没有找到是什么原因造成的，你可以暂时这样获取返回值
setTimeout(async () =>{
  const url = await dp.create()
}, 10)

**Comment by hairyf** [comment]
已修复
